### ISSUE TITLE
zbox bl-update error: blobber's delegate_wallet is not set

### ISSUE THREAD

**Issue by boddumanohar** [0chain/zboxcli#344]
when I try to update blobber setting using the command:

```
zbox bl-update --blobber_id f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25 --read_price 1.0 --write_price 1.2 --min_stake 1.0 --max_stake 5.0
```
I get this error in return
```
update_blobber_settings_failed: blobber's delegate_wallet is not set
```

**Comment by Manish-210** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/58730178/217227689-b41088ab-7f58-449e-8e0a-0a5c198108ce.png">

There is an error while updating the blobber settings but I am getting a different error `update_blobber_settings_failed: access denied, allowed for delegate_wallet owner only`. How to recreate the error you got? It is certainly because of a mismatch of delegate_wallet in 0chain/code/go/0chain.net/smartcontract/storagesc/blobber.go

@dabasov @boddumanohar

**Comment by dabasov** [comment]
settings can be updated only with delegate wallet, so you should use it for bl-update

**Comment by boddumanohar** [comment]
closing this issue as the `bl-update` feature is working as expected as documented here: https://github.com/0chain/blobber/issues/628

**Comment by aniketsingh03** [comment]
Re-opening this as I am also facing this issue. Need to investigate more.

**Comment by boddumanohar** [comment]
this happens only for a specific blobber "f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25" . When I created this ticket, this blobber ID was generated from the local network setup. It could be possible that there is something wrong with that setup. 

But since this issue doesn't happen in case of chimeny blobbers or the blobbers that we deploy, this issue can be closed.
